### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by WASasquatch** [opensource-socialnetwork/opensource-socialnetwork#433]
Why is it I have a `default.php` theme file, yet changing something as simple as the background color is overwritten by a inline background 

***default.php***
```css
body {
font-size: 11px;
font-family:"lucida grande",tahoma,verdana,arial,sans-serif;
color: #333;
background: url(<?php echo ossn_site_url(); ?>themes/ossnblack/images/background.jpg) no-repeat center center fixed; 
-webkit-background-size: cover;
-moz-background-size: cover;
-o-background-size: cover;
background-size: cover;
}
```

Overwritten somewhere inline on line 113
```css
 body {
        background: #FDFDFD;
    } 
```

Sorta defeats the whole purpose of the theme.
